apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
  namespace: default
spec:
  instances: 3
  storage:
    storageClass: longhorn
    size: 10Gi
  bootstrap:
    initdb:
      database: mydb
      owner: myuser
      secret:
        name: myuser-secret
